version: "3.9"

services:
  db_pythonweb:
    image: postgres:latest
    container_name: db_pythonweb
    restart: no
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
