version: "3.9"

services:
  db_pythonweb:
    image: postgres:latest
    container_name: db_pythonweb
    restart: no
    ports:
      - "5432:5432"
    expose:
      - "5432"
    env_file:
      - .env
    networks:
      - pythonweb_networks
    volumes:
      - ./volumes/db:/var/lib/postgresql/data

  contacts_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contacts_api
    restart: no
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db_pythonweb
    networks:
      - pythonweb_networks
    volumes:
      - ./src:/app/src

networks:
  pythonweb_networks:
    driver: bridge
